// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Suggests natural methods for managing a identified skin condition.
 *
 * - suggestNaturalCures - A function that suggests natural methods for managing a skin condition.
 * - SuggestNaturalCuresInput - The input type for the suggestNaturalCures function.
 * - SuggestNaturalCuresOutput - The return type for the suggestNaturalCures function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestNaturalCuresInputSchema = z.object({
  diseaseName: z.string().describe('The name of the identified skin disease.'),
});
export type SuggestNaturalCuresInput = z.infer<typeof SuggestNaturalCuresInputSchema>;

const SuggestNaturalCuresOutputSchema = z.object({
  naturalCures: z
    .array(z.string())
    .describe('A list of natural methods for managing the identified skin disease.'),
});
export type SuggestNaturalCuresOutput = z.infer<typeof SuggestNaturalCuresOutputSchema>;

export async function suggestNaturalCures(input: SuggestNaturalCuresInput): Promise<SuggestNaturalCuresOutput> {
  return suggestNaturalCuresFlow(input);
}

const naturalCureTool = ai.defineTool({
  name: 'getNaturalCuresForDisease',
  description: 'Retrieves a list of natural cures for a given skin disease from a knowledge base.',
  inputSchema: z.object({
    diseaseName: z.string().describe('The name of the skin disease to find natural cures for.'),
  }),
  outputSchema: z.array(z.string()),
},
async (input) => {
  const naturalCureMap: { [key: string]: string[] } = {
    eczema: [
      'Apply moisturizer regularly',
      'Avoid scratching',
      'Use mild soaps and detergents',
      'Take lukewarm baths',
      'Apply cool compresses',
      'Try natural remedies like coconut oil or aloe vera',
    ],
    psoriasis: [
      'Moisturize daily',
      'Use medicated creams or ointments',
      'Expose skin to small amounts of sunlight',
      'Avoid triggers like stress and certain foods',
      'Take oatmeal baths',
      'Consider natural treatments like aloe vera or turmeric',
    ],
    acne: [
      'Wash your face gently twice a day',
      'Use non-comedogenic products',
      'Avoid picking or squeezing pimples',
      'Stay hydrated',
      'Eat a healthy diet',
      'Try natural remedies like tea tree oil or honey',
    ],
  };

  const diseaseName = input.diseaseName.toLowerCase();
  if (naturalCureMap[diseaseName]) {
    return naturalCureMap[diseaseName];
  } else {
    return [];
  }
});

const prompt = ai.definePrompt({
  name: 'suggestNaturalCuresPrompt',
  tools: [naturalCureTool],
  input: {schema: SuggestNaturalCuresInputSchema},
  output: {schema: SuggestNaturalCuresOutputSchema},
  prompt: `Suggest natural methods for managing the following skin disease. Use the getNaturalCuresForDisease tool to retrieve the cures.

Disease Name: {{{diseaseName}}}`,
});

const suggestNaturalCuresFlow = ai.defineFlow(
  {
    name: 'suggestNaturalCuresFlow',
    inputSchema: SuggestNaturalCuresInputSchema,
    outputSchema: SuggestNaturalCuresOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
